#!/usr/bin/env sh 

## need to run this 
## limelight --config <path to config file>

limelight -m config width 3 
limelight -m config radius 10 
limelight -m config placement exterior
limelight -m config active_color 0xFF40FF00
limelight -m config normal_color 0x00FFFFFF
